# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # define b as a counter with the prefix as variable a, and seed as 10.
- name: minor1
  value:  $[counter(variables['major1'], 10)]
- name: sic-version
  value: $(minor1)

steps:
- script: |
    echo $(minor1)
    echo $(major1)
    echo $(sic-version)
    echo '---------------'
  displayName: 'Minor version'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $armOutput = @'
      {
          "sqlServerName": {
      	    "value" : "[some sql server name].database.windows.net",
              "type": "string"
          },
          "databaseName": {
      		"value" : "[some sql db name]",
              "type": "string"
          }
      }
      '@
      write-host "received: $($armOutput)"
      $armOutputObj = $armOutput | convertfrom-json
      Write-Host $armOutpuObj
      $armOutputObj.PSObject.Properties | ForEach-Object {
          $keyname = $_.Name
          $value = $_.Value.value
          ## Creates a standard pipeline variable
          Write-Output "##vso[task.setvariable variable=$keyName;]$value"
      		
          ## Creates an output variable
          Write-Output "##vso[task.setvariable variable=$keyName;isOutput=true]$value"
          Write-Host "##vso[task.setvariable variable=test;]testvalue"
      }

- script: |
    echo "sqlServerName is $(sqlServerName)"
    echo "databaseName from variable $(databaseName)" 
    echo "$(System.AccessToken)"

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(2)(a84771c4-d59c-4233-8c65-9e7c8e404eac)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az pipelines variable-group variable update --group-id 5  --name cb_host --value newValue2 --project https://dev.azure.com/info0606/'
    addSpnToEnvironment: true
    useGlobalConfig: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $putUrl = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/distributedtask/variablegroups/5?api-version=6.1-preview.2"
      $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/distributedtask/variablegroups?groupName=naeem-gluu2&api-version=6.1-preview.2"
              Write-Host "URL: $url"
              $authHeader = @{Authorization = "Bearer $(System.AccessToken)"}

              Write-Host "system token: $(System.AccessToken)"
              $pipeline = Invoke-RestMethod -Uri $url -Headers $authHeader

              Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"
              Write-Host $pipeline.value
              # Update an existing variable named cb_host to its new value 1035
              $pipeline.value.variables.cb_host.Value = "1035"

              ####****************** update the modified object **************************
              $json = @($pipeline) | ConvertTo-Json -Depth 99
              Write-Host $json
              $updatedef = Invoke-RestMethod -Method Put -Uri $putUrl -Headers $authHeader -ContentType "application/json" -Body ([System.Text.Encoding]::UTF8.GetBytes($json))
              write-host "==========================================================" 
              Write-host "The value of Varialbe 'cb_host' is updated to" $updatedef.value.variables.v1030.value
              write-host "=========================================================="

#https://cloudarchitected.com/2019/10/updating-variable-groups-from-an-azure-devops-pipeline/
# https://developercommunity.visualstudio.com/content/problem/639518/update-single-variable-in-variable-group-which-has.html
- bash: |
     baseUri="https://dev.azure.com/info0606/info/_apis/distributedtask/variablegroups/5?api-version=5.1"
     curl -fL -X PUT $baseUri -H "Authorization:Bearer $(System.AccessToken)" -H "Content-Type:application/json" \
     -d '{
       "id": 5,
       "description": "variable group for gluu",
       "type": "Vsts",
       "name": "naeem-gluu2",
       "variableGroupProjectReferences": {
           "description": "",
           "name": "info",
           "projectReference": {
               "id": "32be4b0e-237f-430d-9289-c5966a5c9829",
               "name": "info@nqtech.ca"
           }
       },
       "variables": {
         "cb_host": {
           "isSecret": false,
           "value": "$(sqlServerName)"
         }
       }
     }'
  displayName: 'Set variable in variable group to current foo'

