# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:

  # define b as a counter with the prefix as variable a, and seed as 10.
- name: minor1
  value:  $[counter(variables['major1'], 10)]
- name: sic-version
  value: $(minor1)

steps:
- script: |
    echo $(minor1)
    echo $(major1)
    echo $(sic-version)
    echo '---------------'
  displayName: 'Minor version'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $armOutput = @'
      {
          "sqlServerName": {
      	    "value" : "[some sql server name].database.windows.net",
              "type": "string"
          },
          "databaseName": {
      		"value" : "[some sql db name]",
              "type": "string"
          }
      }
      '@
      $armOutputObj = $armOutput | convertfrom-json
      $armOutputObj.PSObject.Properties | ForEach-Object {
          $keyname = $_.Name
          $value = $_.Value.value
          ## Creates a standard pipeline variable
          Write-Output "##vso[task.setvariable variable=$keyName;]$value"
      		
          ## Creates an output variable
          Write-Output "##vso[task.setvariable variable=$keyName;isOutput=true]$value"
      }
  
- script: |
    echo "sqlServerName is $(sqlServerName)"
    echo "databaseName from variable $(databaseName)" 

#https://cloudarchitected.com/2019/10/updating-variable-groups-from-an-azure-devops-pipeline/
# https://developercommunity.visualstudio.com/content/problem/639518/update-single-variable-in-variable-group-which-has.html
- bash: |
     
     $baseUri = "https://dev.azure.com/BIA-Platform/${prjid}/_apis/distributedtask/variablegroups/237?api-version=5.0-preview.1"
     curl -fL -XPUT -H "Authorization:Bearer $(System.AccessToken)" -H "Content-Type:application/json" \
     -d '{
       "id": "$(FOO_VARIABLE_GROUP_ID)",
       "type": "Vsts",
       "name": "Foo",
       "variables": {
         "FOO_VARIABLE_GROUP_ID": {
           "isSecret": false,
           "value": "$(FOO_VARIABLE_GROUP_ID)"
         },
         "FOO": {
           "isSecret": false,
           "value": "$(valueIWantToSet)"
         }
       }
     }' \
     $(System.TeamFoundationCollectionUri)/$(System.TeamProject)/_apis/distributedtask/variablegroups/$(FOO_VARIABLE_GROUP_ID)?api-version=5.0-preview.1
  displayName: 'Set variable in variable group to current foo'

